#!/usr/bin/python3.8

import os
import subprocess


def format_code(dir, ext):
    for path, sub_dirs, files in os.walk(dir):
        for name in files:
            if name.endswith(ext):
                print("Formating file {}/{}".format(path, name));
                subprocess.call(["clang-format", "-i", "{}".format(os.path.join(path, name))])

format_code("source", ".cpp")
format_code("include", ".hpp")
format_code("tests", ".cpp")